"""add danh_sach_tac_gia column

Revision ID: 5c905909e135
Revises: bd3c37b0d3af
Create Date: 2026-07-06 15:13:53.819394

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5c905909e135"
down_revision: str | None = "bd3c37b0d3af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "initiatives",
        sa.Column("danh_sach_tac_gia", sa.Text(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("initiatives", "danh_sach_tac_gia")
    # ### end Alembic commands ###
