"""Initial baseline tables

Revision ID: 7171a532f566
Revises:
Create Date: 2026-07-06 09:32:03.348261

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7171a532f566"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initiatives",
        sa.Column("ten", sa.String(length=500), nullable=False),
        sa.Column(
            "linh_vuc",
            sa.Enum(
                "CONG_NGHE",
                "QUY_TRINH",
                "AN_TOAN",
                "MOI_TRUONG",
                "KHAC",
                name="linhvuc",
            ),
            nullable=False,
        ),
        sa.Column("tac_gia", sa.String(length=255), nullable=False),
        sa.Column("dong_tac_gia", sa.String(length=500), nullable=False),
        sa.Column("don_vi", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("tom_tat", sa.Text(), nullable=False),
        sa.Column("hieu_qua", sa.Text(), nullable=False),
        sa.Column("quan_tam", sa.Integer(), nullable=False),
        sa.Column(
            "trang_thai",
            sa.Enum("CHO_DUYET", "DA_DUYET", name="trangthai"),
            nullable=False,
        ),
        sa.Column("diem", sa.Integer(), nullable=False),
        sa.Column("giai_thuong", sa.String(length=255), nullable=False),
        sa.Column(
            "ngay_nop",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_logs_timestamp"), "system_logs", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_user_email"), "system_logs", ["user_email"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("GUEST", "ADMIN", name="userrole"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("initiative_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("minio_object_name", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["initiative_id"], ["initiatives.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_logs_user_email"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_timestamp"), table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_table("initiatives")
    # ### end Alembic commands ###
