"""add template fields to initiatives

Revision ID: bd3c37b0d3af
Revises: 7171a532f566
Create Date: 2026-07-06 13:45:50.265929

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bd3c37b0d3af"
down_revision: str | None = "7171a532f566"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "initiatives",
        sa.Column("thoi_gian", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "initiatives",
        sa.Column("ly_do", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "initiatives",
        sa.Column("muc_tieu", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "initiatives",
        sa.Column("thuc_trang", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "initiatives",
        sa.Column("giai_phap", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "initiatives",
        sa.Column("cach_thuc", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "initiatives",
        sa.Column("tinh_moi", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "initiatives",
        sa.Column("nhan_rong", sa.Text(), nullable=False, server_default=""),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("initiatives", "nhan_rong")
    op.drop_column("initiatives", "tinh_moi")
    op.drop_column("initiatives", "cach_thuc")
    op.drop_column("initiatives", "giai_phap")
    op.drop_column("initiatives", "thuc_trang")
    op.drop_column("initiatives", "muc_tieu")
    op.drop_column("initiatives", "ly_do")
    op.drop_column("initiatives", "thoi_gian")
    # ### end Alembic commands ###
